import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.MIMOCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
let modelsData = "{}"
if (process.env.MODELS_DEV_API_JSON) {
  try {
    const text = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    JSON.parse(text)
    modelsData = text
  } catch {}
} else {
  try {
    const res = await fetch(`${modelsUrl}/api.json`, {
      signal: AbortSignal.timeout(1000),
    })
    if (res.ok) {
      const text = await res.text()
      JSON.parse(text)
      modelsData = text
    }
  } catch {}
}
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
