blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/XiaomiMiMo/MiMo-Code/issues/new?template=question.yml
    about: For quick questions. Note that issues are searchable and help others with the same question.
