id = "mimocode"
name = "MiMoCode"
description = "The open source coding agent."
version = "0.1.0"
schema_version = 1
authors = ["XiaomiMiMo"]
repository = "https://github.com/XiaomiMiMo/MiMo-Code"

[agent_servers.mimocode]
name = "MiMoCode"
icon = "./icons/opencode.svg"

[agent_servers.mimocode.targets.darwin-aarch64]
archive = "https://github.com/XiaomiMiMo/MiMo-Code/releases/download/v0.1.0/mimocode-darwin-arm64.zip"
cmd = "./mimo"
args = ["acp"]

[agent_servers.mimocode.targets.darwin-x86_64]
archive = "https://github.com/XiaomiMiMo/MiMo-Code/releases/download/v0.1.0/mimocode-darwin-x64.zip"
cmd = "./mimo"
args = ["acp"]

[agent_servers.mimocode.targets.linux-aarch64]
archive = "https://github.com/XiaomiMiMo/MiMo-Code/releases/download/v0.1.0/mimocode-linux-arm64.tar.gz"
cmd = "./mimo"
args = ["acp"]

[agent_servers.mimocode.targets.linux-x86_64]
archive = "https://github.com/XiaomiMiMo/MiMo-Code/releases/download/v0.1.0/mimocode-linux-x64.tar.gz"
cmd = "./mimo"
args = ["acp"]

[agent_servers.mimocode.targets.windows-x86_64]
archive = "https://github.com/XiaomiMiMo/MiMo-Code/releases/download/v0.1.0/mimocode-windows-x64.zip"
cmd = "./mimo.exe"
args = ["acp"]
