id = "mimocode"
name = "MiMoCode"
description = "The open source coding agent."
version = "1.14.19"
schema_version = 1
authors = ["XiaoMi"]
repository = "https://github.com/XiaoMi/MiMo-Code"

[agent_servers.mimocode]
name = "MiMoCode"
icon = "./icons/opencode.svg"

[agent_servers.mimocode.targets.darwin-aarch64]
archive = "https://github.com/XiaoMi/MiMo-Code/releases/download/v1.14.19/opencode-darwin-arm64.zip"
cmd = "./opencode"
args = ["acp"]

[agent_servers.mimocode.targets.darwin-x86_64]
archive = "https://github.com/XiaoMi/MiMo-Code/releases/download/v1.14.19/opencode-darwin-x64.zip"
cmd = "./opencode"
args = ["acp"]

[agent_servers.mimocode.targets.linux-aarch64]
archive = "https://github.com/XiaoMi/MiMo-Code/releases/download/v1.14.19/opencode-linux-arm64.tar.gz"
cmd = "./opencode"
args = ["acp"]

[agent_servers.mimocode.targets.linux-x86_64]
archive = "https://github.com/XiaoMi/MiMo-Code/releases/download/v1.14.19/opencode-linux-x64.tar.gz"
cmd = "./opencode"
args = ["acp"]

[agent_servers.mimocode.targets.windows-x86_64]
archive = "https://github.com/XiaoMi/MiMo-Code/releases/download/v1.14.19/opencode-windows-x64.zip"
cmd = "./opencode.exe"
args = ["acp"]
